owner: TinDevVN # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - hnguyen1910
skipDeleteIssues: true
skipTopicsUpdate: true

sites:
  - name: Homepage
    url: https://tinvn.eu.org
  # - name: Link Shortener (basic)
  #   url: https://r.tinvn.eu.org
  # - name: Link Shortener (discord.gg links)
  #   url: https://d.tinvn.eu.org
  # - name: Files
  #   url: https://fs.tinvn.eu.org
  - name: NoPaste
    url: https://nopaste.tinvn.eu.org
  # - name: NPaste
  #   url: https://paste.tinvn.eu.org
  - name: Discord Bot
    url: https://tinoy.tinvn.eu.org
  - name: This status page
    url: https://status.tinvn.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tinvn.eu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HNStatus
  introTitle: ":)"
  introMessage: This page powered entirely by GitHub.
  navbar:
    - title: Home
      href: https://tinvn.eu.org\
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: "ocean"

commitMessages:
  commitAuthorName: "HN B0T"
  commitAuthorEmail: "ghbot@ti.nz.eu.org"

user-agent: hnguyen1910
